// <auto-generated />
using System;
using BIS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424212127_AddRececoes")]
    partial class AddRececoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BIS.Domain.Entities.Devolucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSincronizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorReembolsado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("VendaOriginalId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DataDevolucao");

                    b.HasIndex("LojaId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("VendaOriginalId");

                    b.ToTable("Devolucoes");
                });

            modelBuilder.Entity("BIS.Domain.Entities.FechoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ContadoMbway")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ContadoMultibanco")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ContadoNumerario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ContadoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("DataFecho")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSincronizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Discrepancia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Justificacao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<bool>("TemDiscrepancia")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TeoricoMbway")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TeoricoMultibanco")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TeoricoNumerario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TeoricoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataFecho");

                    b.HasIndex("LojaId");

                    b.HasIndex("OperadorId");

                    b.ToTable("FechosCaixa");
                });

            modelBuilder.Entity("BIS.Domain.Entities.LinhaDevolucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DevolucaoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DevolucaoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("LinhasDevolucao");
                });

            modelBuilder.Entity("BIS.Domain.Entities.LinhaRececao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<Guid>("RececaoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RececaoId");

                    b.ToTable("LinhasRececao");
                });

            modelBuilder.Entity("BIS.Domain.Entities.LinhaTransferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<Guid>("TransferenciaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TransferenciaId");

                    b.ToTable("LinhasTransferencia");
                });

            modelBuilder.Entity("BIS.Domain.Entities.LinhaVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId", "ProdutoId");

                    b.ToTable("LinhasVenda");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("EstadoRede")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Localidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UltimaSincronizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<decimal>("PVP")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Perecivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecoCusto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EAN")
                        .IsUnique();

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Quebra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSincronizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<byte>("Motivo")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPerdido")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("LojaId", "DataRegisto");

                    b.ToTable("Quebras");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Rececao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataRececao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSincronizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLinhas")
                        .HasColumnType("int");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<int>("TotalUnidades")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataRececao");

                    b.HasIndex("LojaId");

                    b.HasIndex("OperadorId");

                    b.ToTable("Rececoes");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSincronizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("LojaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("LojaOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLinhas")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TotalUnidades")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransferenciaEnvioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DataMovimento");

                    b.HasIndex("LojaDestinoId");

                    b.HasIndex("LojaOrigemId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("TransferenciaEnvioId");

                    b.HasIndex("TipoMovimento", "TransferenciaEnvioId")
                        .IsUnique()
                        .HasFilter("[TransferenciaEnvioId] IS NOT NULL");

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("EstadoConta")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("LojaBaseId")
                        .HasColumnType("int");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("Perfil")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("PinPOS")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("Email IS NOT NULL");

                    b.HasIndex("LojaBaseId");

                    b.HasIndex("NIF")
                        .IsUnique();

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataSincronizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<byte>("MetodoPagamento")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("NifCliente")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataSincronizacao");

                    b.HasIndex("OperadorId");

                    b.HasIndex("LojaId", "DataTransacao");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Devolucao", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Utilizador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Venda", "VendaOriginal")
                        .WithMany()
                        .HasForeignKey("VendaOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Operador");

                    b.Navigation("VendaOriginal");
                });

            modelBuilder.Entity("BIS.Domain.Entities.FechoCaixa", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Loja", "Loja")
                        .WithMany("Fechos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Utilizador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("BIS.Domain.Entities.LinhaDevolucao", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Devolucao", "Devolucao")
                        .WithMany("Linhas")
                        .HasForeignKey("DevolucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devolucao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BIS.Domain.Entities.LinhaRececao", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Rececao", "Rececao")
                        .WithMany("Linhas")
                        .HasForeignKey("RececaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Rececao");
                });

            modelBuilder.Entity("BIS.Domain.Entities.LinhaTransferencia", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Transferencia", "Transferencia")
                        .WithMany("Linhas")
                        .HasForeignKey("TransferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Transferencia");
                });

            modelBuilder.Entity("BIS.Domain.Entities.LinhaVenda", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Venda", "Venda")
                        .WithMany("Linhas")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Quebra", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Loja", "Loja")
                        .WithMany("Quebras")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Utilizador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Operador");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Rececao", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Utilizador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Transferencia", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Loja", "LojaDestino")
                        .WithMany("TransferenciasRecebidas")
                        .HasForeignKey("LojaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Loja", "LojaOrigem")
                        .WithMany("TransferenciasEnviadas")
                        .HasForeignKey("LojaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Utilizador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Transferencia", "Envio")
                        .WithMany()
                        .HasForeignKey("TransferenciaEnvioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Envio");

                    b.Navigation("LojaDestino");

                    b.Navigation("LojaOrigem");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Utilizador", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Loja", "LojaBase")
                        .WithMany("Utilizadores")
                        .HasForeignKey("LojaBaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LojaBase");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Venda", b =>
                {
                    b.HasOne("BIS.Domain.Entities.Loja", "Loja")
                        .WithMany("Vendas")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BIS.Domain.Entities.Utilizador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loja");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Devolucao", b =>
                {
                    b.Navigation("Linhas");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Loja", b =>
                {
                    b.Navigation("Fechos");

                    b.Navigation("Quebras");

                    b.Navigation("TransferenciasEnviadas");

                    b.Navigation("TransferenciasRecebidas");

                    b.Navigation("Utilizadores");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Rececao", b =>
                {
                    b.Navigation("Linhas");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Transferencia", b =>
                {
                    b.Navigation("Linhas");
                });

            modelBuilder.Entity("BIS.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Linhas");
                });
#pragma warning restore 612, 618
        }
    }
}
